language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: 
  - sudo apt-get install python-numpy python-scipy libatlas-dev libatlas3gf-base python-sklearn
# command to run tests
script: nosetests