language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
sudo : false
cache:
  directories: 
    - $PWD/wheelhouse
install: 
script:
  - pip wheel .
  - pip install .
# command to run tests
script: nosetests