language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install: 
  - "sudo apt-get install gcc gfortran python-dev libblas-dev liblapack-dev cython"
  - "pip install ."
# command to run tests
script: nosetests