language: python
python:
  - "2.7"

# command to install dependencies\
cache: pip
sudo: false
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
      - python-scipy
      - python-numpy
      - libatlas-dev
      - libatlas3gf-base
      - libblas-dev
      - liblapack-dev
      - python-matplotlib
      - gfortran
      - python-tk
install:
  - virtualenv --system-site-packages testvenv
  - source testvenv/bin/activate
  - pip install pip --upgrade
  - pip install coverage codecov nose scikit-learn seaborn six pandas
  - python setup.py build install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to run tests
script: nosetests  --with-coverage --cover-package=pyriemann
after_success:
  - codecov
