language: python
python:
  - "2.7"
#  - "3.4"
# command to install dependencies\
cache: pip
sudo: false
addons:
  apt:
    packages:
      - python-scipy
      - python-numpy
      - libatlas-dev
      - libatlas3gf-base
      - libblas-dev
      - liblapack-dev
      - python-matplotlib
      - python-pandas
      - python-sklearn
      - gfortran
install:
  #- virtualenv --system-site-packages testvenv
  #- source testvenv/bin/activate
  - pip install pip --upgrade
  - pip install coverage python-coveralls nose
  - python setup.py install
# command to run tests
script: nosetests  --with-coverage --cover-package=pyriemann
after_success:
  #- deactivate
  #- pip install python-coveralls --upgrade
  - coveralls
